pimcore:
  objects:
    class_definitions:
      data:
        map:
          remoteSelect: Savosik\RemoteFieldsBundle\Model\Object\Data\RemoteSelect
          remoteMultiSelect: Savosik\RemoteFieldsBundle\Model\Object\Data\RemoteMultiSelect